### ISSUE TITLE
Thank you for making this :)

### ISSUE THREAD

**Issue by Tylersuard** [jcrygier/NodeMCUSimulator#6]
This might be a silly question, given that it's written in Java, but can I use Micropython on this simulator?

**Comment by jcrygier** [comment]
This program is pretty heavily geared towards using Lua (via Lua4J), so it can't be used for Micropython as-is.

However, I could see using the same concept to utilize Jython (http://www.jython.org/) to do what you're talking about.  Would likely be a different project though.
